### ISSUE TITLE
Workflow concerning build of react components and compilation of scss

### ISSUE THREAD

**Issue by tobias74** [it-at-m/eappointment#205]
Currently we build the react application and compile the scss on the developer machine before committing. This leads to merge conflicts in case more than one developer has worked on the React components or the scss. 

Additionally given our current branching concept we will then have to resolve the same merge conflict multiple times (merging feature on dev, then merging the same feature on test, then on main).

Maybe we can find a solution that integrates the build process in the pipeline?

**Comment by ThomasAFink** [comment]
These are now built in the Github actions.
