### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by darkdragon-001** [it-at-m/eappointment#427]
There is no `LICENSE` file in this repository. This makes it difficult for other to re-use the contents of this repository. See https://choosealicense.com/no-permission/ on why this is a problem.

**Comment by ThomasAFink** [comment]
Thank you for pointing this out! I’ve added an EUPL v1.2 license to the repository, which allows for re-use of the content under the terms of this license. You can now find the license file [here](https://github.com/it-at-m/eappointment/blob/next/LICENSE).

For more information about the EUPL, please see [the official site](https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12).

Let me know if you have any further questions!
